;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt --enable-reference-types --enable-gc --merge-similar-functions -S -o - | filecheck %s

(module
  ;; CHECK:      (type $none_=>_i32 (func (result i32)))

  ;; CHECK:      (type $i32_=>_i32 (func (param i32) (result i32)))

  ;; CHECK:      (func $big-const-42 (type $none_=>_i32) (result i32)
  ;; CHECK-NEXT:  (call $byn$mgfn-shared$big-const-42
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $big-const-42 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (i32.const 42)
  )

  ;; same as $big-const-42, but the set of $big-const-* derives {42, 42, 43} params
  ;; CHECK:      (func $big-const-42-1 (type $none_=>_i32) (result i32)
  ;; CHECK-NEXT:  (call $byn$mgfn-shared$big-const-42
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $big-const-42-1 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (i32.const 42)
  )
  ;; CHECK: 