;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: wasm-opt %s --optimize-instructions --nominal --roundtrip --all-features -S -o - | filecheck %s
;; roundtrip to see the effects on heap types in the binary format, specifically
;; regarding nominal heap types

(module
 ;; Create multiple different signature types, all identical structurally but
 ;; distinct nominally. The three tables will use different ones, and the
 ;; emitted call_indirects should use the corresponding ones.

 ;; CHECK:      (type $v1 (func))
 (type $v1 (func))

 ;; CHECK:      (type $v2 (func))
 (type $v2 (func))

 ;; CHECK:      (type $v3 (func))
 (type $v3 (func))

 ;; CHECK:      (type $i32_=>_none (func (param i32)))

 ;; CHECK:      (table $table-1 10 (ref null $v1))
 (table $table-1 10 (ref null $v1))

 ;; CHECK:      (table $table-2 10 (ref null $v2))
 (table $table-2 10 (ref null $v2))

 ;; CHECK:      (table $table-3 10 (ref null $v3))
 (table $table-3 10 (ref null $v3))

 ;; CHECK:      (elem $elem-1 (table $table-1) (i32.const 0) (ref