;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --generate-stack-ir --optimize-stack-ir \
;; RUN:   -all --print-stack-ir | filecheck %s

(module
  ;; CHECK:      (tag $e0 (param i32))
  (tag $e0 (param i32))

  ;; CHECK:      (func $eh (type $none_=>_none)
  ;; CHECK-NEXT:  try $l0
  ;; CHECK-NEXT:   i32.const 0
  ;; CHECK-NEXT:   throw $e0
  ;; CHECK-NEXT:  ca