;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; Check that extern conversion instructions are emitted properly in the binary format.
;; Also check that the optimizer does not break on this code.

;; RUN: wasm-opt %s -all -O1 --roundtrip -S -o - | filecheck %s


(module
 ;; CHECK:      (type $ref|any|_=>_ref|extern| (func (param (ref any)) (result (ref extern))))

 ;; CHECK:      (type $externref_=>_anyref (func (param externref