;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-as %s -all -g -o %t.wasm
;; RUN: wasm-dis %t.wasm -o - | filecheck %s

(module
 ;; CHECK:      (type $0 (func))
 (type $0 (func))
 ;; CHECK:      (memory $appMemory (shared i64 23 256))
 (memory $appMemory (shared i64 23 256))
 ;; CHECK:      (memory $dataMemory (shared i64 23 256))
 (memory $dataMemory (shared i64 23 256))
 ;; CHECK:      (memory $instrumentMemory (shared i64 23 256))
 (memory $instrumentMemory (shared i64 23 256))
 ;; CHECK:      (func $atomic-lo